WebUI/Models/CustomerViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace WebUI.Models
{
    public class CustomerViewModel
    {
        [Display(Name = "FullName")]
        public string FullName { get; set; }

        [Display(Name = "City")]
        public string City { get; set; } 

        [Display(Name = "PhoneNumber")]
        public string PhoneNumber { get; set; }
    }
}

WebUI/Models/ErrorViewModel.cs
namespace WebUI.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WebUI/Controllers/CultureController.cs
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Mvc;

namespace WebUI.Controllers
{
    public class CultureController : Controller
    {
        [HttpPost]
        public IActionResult SetLanguage(string culture, string returnUrl)
        {
            Response.Cookies.Append(
                CookieRequestCultureProvider.DefaultCookieName,
                CookieRequestCultureProvider.MakeCookieValue(new RequestCulture(culture)),
                new CookieOptions { Expires = DateTimeOffset.UtcNow.AddYears(1) }
            );

            return LocalRedirect(returnUrl);
        }
    }
}

WebUI/Controllers/CustomerController.cs
using Microsoft.AspNetCore.Mvc;
using WebUI.Resources;

namespace WebUI.Controllers
{
    public class CustomerController : Controller
    {
        private readonly LocalizationService _localizationService;

        public CustomerController(LocalizationService localizationService)
        {
            _localizationService = localizationService;
        }

        public IActionResult Index()
        {
            var fullName = _localizationService.GetLocalizedHtmlString("FullName");
            var city = _localizationService.GetLocalizedHtmlString("City");
            var phoneNumber = _localizationService.GetLocalizedHtmlString("PhoneNumber");
            
            return View();
        }
    }
}

WebUI/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using WebUI.Models;

namespace WebUI.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WebUI/Views/Customer/Index.cshtml
@using WebUI.Resources
@inject LocalizationService LocalizationService
@model CustomerViewModel
@{
    ViewData["Title"] = "Create";
}

<div class="card">
    <div class="card-header">Create</div>
    <div class="card-body">
        <form asp-controller="Customer" asp-action="Create" method="post">
            <div class="form-row">
                <div class="col">
                    <label asp-for="FullName"></label>
                    <input asp-for="FullName" 
                        placeholder="@LocalizationService.GetLocalizedHtmlString("FullName")" 
                        class="form-control" />
                    <span asp-validation-for="FullName"></span>
                </div>
                <div class="col">
                    <label asp-for="City"></label>
                    <input asp-for="City" 
                        placeholder="@LocalizationService.GetLocalizedHtmlString("City")" 
                        class="form-control" />
                    <span asp-validation-for="City"></span>
                </div>
                <div class="col">
                    <label asp-for="PhoneNumber"></label>
                    <input asp-for="PhoneNumber" 
                        placeholder="@LocalizationService.GetLocalizedHtmlString("PhoneNumber")" 
                        class="form-control" />
                    <span asp-validation-for="PhoneNumber"></span>
                </div>
            </div>
            <div class="clearfix"></div>
            <div class="form-row">
                <div class="col">
               <button style="margin-top: 10px" class="btn btn-success" type="submit"> Submit</button>
                </div>
            </div>
        </form>
    </div>
</div>

WebUI/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebUI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebUI.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebUI</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Customer" asp-action="Index">Customer</a>
                        </li>
                    </ul>
                    <div class="language">
                        @await Html.PartialAsync("_SetLanguagePartial")
                    </div>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - WebUI - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

WebUI/Views/Shared/_SetLanguagePartial.cshtml
@using Microsoft.AspNetCore.Builder
@using Microsoft.AspNetCore.Localization
@using Microsoft.AspNetCore.Mvc.Localization
@using Microsoft.Extensions.Options

@inject IViewLocalizer Localizer
@inject IOptions<RequestLocalizationOptions> LocOptions
@{
    var requestCulture = Context.Features.Get<IRequestCultureFeature>();
    var cultureItems = LocOptions.Value.SupportedUICultures
        .Select(c => new SelectListItem { Value = c.Name, Text = c.DisplayName })
        .ToList();
}

<div>
    <form asp-controller="Culture"
          asp-action="SetLanguage"
          asp-route-returnUrl="@Context.Request.Path"
          method="post">
        Language:
        <select name="culture"
                onchange="this.form.submit();"
                asp-for="@requestCulture.RequestCulture.UICulture.Name"
                asp-items="cultureItems">
        </select>
    </form>
</div>